apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
data:
  POSTGRES_PASSWORD: aGNfcGFzc3dvcmQ=  # base64 encoded 'hc_password'
  DART_API_KEY: ZTllMzkyYzk4OWM0Y2QzMjk1N2E0MmVhODRmZmI4ZTFlMDI5MGNkZQ==  # base64 encoded API key 